### ISSUE TITLE
New release required

### ISSUE THREAD

**Issue by rockerbacon** [pusher/push-notifications-node#46]
#45 removed dependency on some deprecated packages ([request](https://github.com/request/request)) but it seems this was never released to NPM.

I ran into [https://github.com/request/request-promise/issues/247](https://github.com/request/request-promise/issues/247) after getting v1.2.1 from NPM. A release to get this problem fixed would be greatly appreciated.

**Comment by gileswells** [comment]
I've forwarded this to our engineering team to be resolved.
Thank you.

**Comment by elverkilde** [comment]
hi @rockerbacon , sorry about that. I have released version `1.2.2` and `1.2.3`, which includes automated release actions so we can avoid this in the future.
