### ISSUE TITLE
TypeScript definition does not match function result

### ISSUE THREAD

**Issue by zachweinberg** [pusher/push-notifications-node#53]
Hi, I was using this library and the result of `generateToken` did not match the TS defs. I made a PR here: https://github.com/pusher/push-notifications-node/pull/52

Thanks!

**Comment by ghost23** [comment]
What about this? Why was the PR closed @zachweinberg ?

**Comment by zachweinberg** [comment]
@ghost23 I forget :)

**Comment by sonologico** [comment]
Fixed in 1.2.6. Thanks!
