### ISSUE TITLE
type issue 

### ISSUE THREAD

**Issue by imohitagrwal** [pusher/push-notifications-node#58]
generateToken return type is not correct, the type in code is string but it is returning {
token: string
}

please resolve this asap, need to integrate it in our application.

**Comment by benjamin-tang-pusher** [comment]
Hi, returning a dictionary key:value pair for this function is intentional, and I can't see where it would return string. Could you describe in more detail where you're seeing the string return?

I also gave this a go in my typescript app and the function worked fine.

**Comment by benjamin-tang-pusher** [comment]
I will close this issue, but if you have further details let us know by reopening this.
