### ISSUE TITLE
Type issues with APNS

### ISSUE THREAD

**Issue by kieranm** [pusher/push-notifications-node#63]
Hi all,

The following fields [supported by APNS](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification) seem to be missing from the APS types...

- `target-content-id`
- `mutable-content`
- `interruption-level`
- `relevance-score`
- `filter-criteria`

`subtitle` also appears to be missing from the Alert type.
Both `title` and `description` are marked as required in the types – is this correct?

Thanks
Kieran

**Comment by swey** [comment]
Yes, I can confirm this. The properties added in the last iOS version are missing. But at least they work.

More important: `sound` can now be an object with different properties (=> `sound: string | { critical?: number; name: string; volume?: number; }`).
But this is not only a typing issue, the functionality is blocked by Pusher's server side validation. This needs to be adjusted by Pusher.

**Comment by benjamin-tang-pusher** [comment]
Hi, I will add this as an enhancement request for our product team to evaluate.
