### ISSUE TITLE
Cloudflare Workers support

### ISSUE THREAD

**Issue by mglikesbikes** [pusher/push-notifications-node#64]
Hello! Wanted to reach out and ask if this library has been tested on Cloudflare Workers. Workers uses V8 (and does polyfill some node libraries) which leads to interesting problems sometimes.

Thanks in advance!

**Comment by benw-pusher** [comment]
We haven't tested the library with Workers at this time. Are you encountering specific issues in this environment?

**Comment by benw-pusher** [comment]
I believe there is a conflict between Cloudflare's [Crypto implementation](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/) and Node's implementation. 
We don't currently have plans to implement changes that would achieve compatibility
