### ISSUE TITLE
Pusher beams returns 401 when you call delete user from from the sdk though token generation works without any issue 

### ISSUE THREAD

**Issue by anyatibrian** [pusher/push-notifications-node#70]

**Comment by benw-pusher** [comment]
I've not been able to replicate this - the user is deleted as expected. A 401 indicates and incorrect API Key, have you verified this is set correctly?.

**Comment by anyatibrian** [comment]
@benw-pusher what I don't get is I was able to use the same key to generate pusher  users token

**Comment by anyatibrian** [comment]
@benw-pusher  has tested it with post man it only returns 200 status code even when the userID is a fake one  and though with wrong secret key it throws the expected error i.e 401
`{
    "error": "Unauthorized",
    "description": "Incorrect Secret Key"
}`

**Comment by benw-pusher** [comment]
Have you ensured your user is registering correctly? Do you see the corresponding event in the Debug Console in the Pusher dashboard? 
Do you receive error messages in the client when calling setUserId?

**Comment by anyatibrian** [comment]
@benw-pusher I think its fine, the issue I had AWS parameter store was returning an older version of the parameter, so I had to delete it and recreate  a new one so that the version is consistent through out.
