### ISSUE TITLE
Set APNs headers when publishing notifications

### ISSUE THREAD

**Issue by htc007** [pusher/push-notifications-node#71]
How do you set APNs headers when publishing notifications? We need to send various push notifications like background and liveactivity.

**Comment by benjamin-tang-pusher** [comment]
I believe you already contacted us about this, but unfortunately this isn't possible. Only keys [listed here are supported](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html?_gl=1*1ou13kc*_gcl_au*MTg1NTE2MDMzMS4xNjg1NTQyNTI3LjkzMjk0NzA3NC4xNjkyMjk0NTk0LjE2OTIyOTYwNDA.#//apple_ref/doc/uid/TP40008194-CH17-SW1). Others we will remove.

I will close this issue.
